# Dependências autorizadas a executar scripts de instalação.
strictDepBuilds: true
allowBuilds:
  '@firebase/util': false
  esbuild: true
  fsevents: true
  protobufjs: false
  re2: false
  sharp: true
  unrs-resolver: true
  workerd: true
